# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/modules/backend/models/commentblacklist/columns.yaml

# Model Class name
modelClass: Backend\Models\CommentBlackList

# List Title
title: backend::lang.comment.blacklist

# Link URL for each record
recordUrl: backend/commentblacklist/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 15

# Display checkboxes next to each record

showTree: false

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



